# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 61f06252d409e2b0e86c262a4400af09343e095fbed8138b1165f75cf8a24510d3c448a4a15ac7e668ce25232a57a1b592ba279aa985bc27ee2bb5965326ddc7

test:
  secret_key_base: abc46022f32c1210d7d2876f0237bdfe012ecc07a6f4afe33c9d5f147c12556a683b569da52872d89d6a58f098fb724e47545c90edb5dcf62faeb298b4468021

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
